# Generated by Django 4.1.7 on 2023-03-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_alter_notes_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
